//
// Created by Maxim Dobryakov on 07/10/2020.
//

#ifndef AGV_REMOTE_CONTROL_ICONSFONT_H
#define AGV_REMOTE_CONTROL_ICONSFONT_H

#include <lvgl/lvgl.h>

LV_FONT_DECLARE(IconsFont)

#define ICO_SYMBOL_WIFI_NOT_CONNECTED   "\u0030"
#define ICO_SYMBOL_WIFI_CONNECTING      "\u0031"
#define ICO_SYMBOL_WIFI_CONNECTED       "\u0032"
#define ICO_SYMBOL_WIFI_FAILED          "\u0033"
#define ICO_SYMBOL_WIFI_QUALITY_25      "\u0034"
#define ICO_SYMBOL_WIFI_QUALITY_50      "\u0035"
#define ICO_SYMBOL_WIFI_QUALITY_75      "\u0036"
#define ICO_SYMBOL_WIFI_QUALITY_100     "\u0037"


#define ICO_SYMBOL_BATTERY_LEVEL_0      "\u0041"
#define ICO_SYMBOL_BATTERY_LEVEL_25     "\u0042"
#define ICO_SYMBOL_BATTERY_LEVEL_50     "\u0043"
#define ICO_SYMBOL_BATTERY_LEVEL_75     "\u0044"
#define ICO_SYMBOL_BATTERY_LEVEL_100    "\u0045"
#define ICO_SYMBOL_BATTERY_CHARGING     "\u0046"

#endif //AGV_REMOTE_CONTROL_ICONSFONT_H
