//
// Created by Maxim Dobryakov on 08/10/2020.
//

#ifndef AGV_REMOTE_CONTROL_MONTSERRAT16FONT_H
#define AGV_REMOTE_CONTROL_MONTSERRAT16FONT_H

#include <lvgl/lvgl.h>

LV_FONT_DECLARE(Montserrat16Font)

#endif //AGV_REMOTE_CONTROL_MONTSERRAT16FONT_H
