//
// Created by Maxim Dobryakov on 08/10/2020.
//

#ifndef AGV_REMOTE_CONTROL_MONTSERRAT14FONT_H
#define AGV_REMOTE_CONTROL_MONTSERRAT14FONT_H

#include <lvgl/lvgl.h>

LV_FONT_DECLARE(Montserrat14Font)

#endif //AGV_REMOTE_CONTROL_MONTSERRAT14FONT_H
